import tkinter

root = tkinter.Tk()
root.title("Styles (Buttons)")
flat = tkinter.Button(root, text="Flat", relief="flat")
flat.pack()
groove = tkinter.Button(root, text="Groove", relief="groove")
groove.pack()
raised = tkinter.Button(root, text="Raised", relief="raised")
raised.pack()
ridge = tkinter.Button(root, text="Ridge", relief="ridge")
ridge.pack()
solid = tkinter.Button(root, text="Solid", relief="solid")
solid.pack()
sunken = tkinter.Button(root, text="Sunken", relief="sunken")
sunken.pack()
root.mainloop()
